require:
  - rubocop-rails

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.0
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'bin/**/*'
    - 'vendor/**/*'
    - 'tmp/**/*'
    - 'node_modules/**/*'

Style/AsciiComments:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: single_quotes
  ConsistentQuotesInMultiline: true

Metrics/MethodLength:
  Max: 20

Layout/LineLength:
  Max: 120